<?php

declare(strict_types=1);

namespace App\Services;

use App\Exports\CategoriesExport;
use App\Imports\CategoriesImport;
use App\Mail\ExportMail;
use App\Models\Category;
use App\Models\GeneralSetting;
use App\Models\MailSetting;
use App\Models\User;
use App\Traits\CheckPermissionsTrait;
use App\Traits\MailInfo;
use Barryvdh\DomPDF\Facade\Pdf as PDF;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;
use Maatwebsite\Excel\Facades\Excel;
use RuntimeException;
use Symfony\Component\HttpKernel\Exception\ConflictHttpException;

/**
 * Service class for Category entity lifecycle operations.
 *
 * Centralizes business logic for Category CRUD, bulk actions, imports/exports,
 * and file handling. Delegates permission checks to CheckPermissionsTrait.
 */
class CategoryService extends BaseService
{
    use CheckPermissionsTrait, MailInfo;

    /**
     * Default storage path for category images when config is missing.
     */
    private const DEFAULT_CATEGORY_IMAGES_PATH = 'images/category';

    /**
     * Default storage path for category icons when config is missing.
     */
    private const DEFAULT_CATEGORY_ICONS_PATH = 'images/category/icon';

    /**
     * Create a new CategoryService instance.
     *
     * @param UploadService $uploadService Handles file uploads for category images and icons.
     * @param ActivityLogService $activityLogService Handles activity logging for audit trail.
     */
    public function __construct(
        private readonly UploadService $uploadService,
        private readonly ActivityLogService $activityLogService
    ) {}

    /**
     * Retrieve a single category by instance.
     *
     * Requires categories-index permission. Use for show/display operations.
     *
     * @param Category $category The category instance to retrieve.
     * @return Category The refreshed category instance.
     */
    public function getCategory(Category $category): Category
    {
        $this->requirePermission('categories-index');

        return $category->fresh(['parent:id,name']);
    }

    /**
     * Retrieve categories with optional filters and pagination.
     *
     * Supports filtering by status, featured_status, sync_status, parent_id and search term.
     * Requires categories-index permission.
     *
     * @param array<string, mixed> $filters Associative array with optional keys: 'status', 'featured_status', 'sync_status', 'parent_id', 'search'.
     * @param int $perPage Number of items per page.
     * @return LengthAwarePaginator<Category> Paginated category collection.
     */
    public function getCategories(array $filters = [], int $perPage = 10): LengthAwarePaginator
    {
        $this->requirePermission('categories-index');

        return Category::query()
            ->with('parent:id,name')
            ->when(isset($filters['status']), fn ($q) =>
                $q->where('is_active', $filters['status'] === 'active')
            )
            ->when(isset($filters['featured_status']), fn ($q) =>
                $q->where('featured', $filters['featured_status'] === 'featured')
            )
            ->when(isset($filters['sync_status']), fn ($q) =>
                $q->where('is_sync_disable', $filters['sync_status'] === 'disabled')
            )
            ->when(isset($filters['parent_id']), fn ($q) =>
                $q->where('parent_id', $filters['parent_id'])
            )
            ->when(! empty($filters['search']), function ($q) use ($filters) {
                $term = "%{$filters['search']}%";
                $q->where(fn ($sub) => $sub
                    ->where('name', 'like', $term)
                    ->orWhere('short_description', 'like', $term)
                    ->orWhere('slug', 'like', $term)
                );
            })
            ->latest()
            ->paginate($perPage);
    }

    /**
     * Get parent category options for select inputs.
     *
     * Requires categories-index permission.
     *
     * @return Collection<int, Category> Active categories with id and name only.
     */
    public function getParentCategoriesForSelect(): Collection
    {
        $this->requirePermission('categories-index');

        return Category::query()
            ->where('is_active', true)
            ->orderBy('name')
            ->select(['id', 'name'])
            ->get();
    }

    /**
     * Create a new category.
     *
     * Handles image and icon upload when present. Slug is auto-generated by the model.
     * Requires categories-create permission.
     *
     * @param array<string, mixed> $data Validated category attributes including optional 'image' and 'icon' UploadedFile.
     * @return Category The created category instance.
     */
    public function createCategory(array $data): Category
    {
        $this->requirePermission('categories-create');

        return DB::transaction(function () use ($data) {
            $data = $this->handleFileUploads($data);
            $data['is_active'] = $data['is_active'] ?? true;
            $data['featured'] = $data['featured'] ?? false;

            $category = Category::create($data);
            $this->activityLogService->log(
                'Created Category',
                (string) $category->id,
                "Category '{$category->name}' was created."
            );

            return $category;
        });
    }

    /**
     * Update an existing category.
     *
     * Replaces existing image/icon when new ones are provided. Requires categories-update permission.
     *
     * @param Category $category The category instance to update.
     * @param array<string, mixed> $data Validated category attributes including optional 'image' and 'icon' UploadedFile.
     * @return Category The updated category instance (refreshed).
     */
    public function updateCategory(Category $category, array $data): Category
    {
        $this->requirePermission('categories-update');

        return DB::transaction(function () use ($category, $data) {
            if (isset($data['image']) && $data['image'] instanceof UploadedFile && $category->image) {
                $this->uploadService->delete($category->image);
            }
            if (isset($data['icon']) && $data['icon'] instanceof UploadedFile && $category->icon) {
                $this->uploadService->delete($category->icon);
            }

            $data = $this->handleFileUploads($data);
            $category->update($data);
            $this->activityLogService->log(
                'Updated Category',
                (string) $category->id,
                "Category '{$category->name}' was updated."
            );

            return $category->fresh();
        });
    }

    /**
     * Delete a category and remove its files from storage.
     *
     * Fails if the category has children or associated products. Requires categories-delete permission.
     *
     * @param Category $category The category instance to delete.
     * @throws ConflictHttpException When category has children or associated products (409 Conflict).
     */
    public function deleteCategory(Category $category): void
    {
        $this->requirePermission('categories-delete');

        if ($category->children()->exists()) {
            throw new ConflictHttpException(
                "Cannot delete category '{$category->name}' because it has child categories."
            );
        }

        if ($category->products()->exists()) {
            throw new ConflictHttpException(
                "Cannot delete category '{$category->name}' because it has associated products."
            );
        }

        DB::transaction(function () use ($category) {
            $this->cleanupFiles($category);
            $category->delete();
            $this->activityLogService->log(
                'Deleted Category',
                (string) $category->id,
                "Category '{$category->name}' was deleted."
            );
        });
    }

    /**
     * Bulk delete categories that have no children and no products.
     *
     * Skips categories with children or products. Returns the count of successfully deleted categories.
     * Requires categories-delete permission.
     *
     * @param array<int> $ids Category IDs to delete.
     * @return int Number of categories successfully deleted.
     */
    public function bulkDeleteCategories(array $ids): int
    {
        $this->requirePermission('categories-delete');

        return DB::transaction(function () use ($ids) {
            $categories = Category::whereIn('id', $ids)
                ->withCount(['products', 'children'])
                ->get();

            $deletedCount = 0;

            foreach ($categories as $category) {
                if ($category->products_count === 0 && $category->children_count === 0) {
                    $this->cleanupFiles($category);
                    $category->delete();
                    $deletedCount++;
                }
            }

            if ($deletedCount > 0) {
                $this->activityLogService->log(
                    'Bulk deleted Categories',
                    (string) $deletedCount,
                    "{$deletedCount} category(ies) were deleted."
                );
            }

            return $deletedCount;
        });
    }

    /**
     * Bulk activate categories by ID.
     *
     * Sets is_active to true for all matching categories. Requires categories-update permission.
     *
     * @param array<int> $ids Category IDs to activate.
     * @return int Number of categories updated.
     */
    public function bulkActivateCategories(array $ids): int
    {
        $this->requirePermission('categories-update');
        $count = Category::whereIn('id', $ids)->update(['is_active' => true]);
        if ($count > 0) {
            $this->activityLogService->log(
                'Bulk activated Categories',
                (string) $count,
                "{$count} category(ies) were activated."
            );
        }

        return $count;
    }

    /**
     * Bulk deactivate categories by ID.
     *
     * Sets is_active to false for all matching categories. Requires categories-update permission.
     *
     * @param array<int> $ids Category IDs to deactivate.
     * @return int Number of categories updated.
     */
    public function bulkDeactivateCategories(array $ids): int
    {
        $this->requirePermission('categories-update');
        $count = Category::whereIn('id', $ids)->update(['is_active' => false]);
        if ($count > 0) {
            $this->activityLogService->log(
                'Bulk deactivated Categories',
                (string) $count,
                "{$count} category(ies) were deactivated."
            );
        }

        return $count;
    }

    /**
     * Bulk enable featured status for categories.
     *
     * Sets featured to true for all matching categories. Requires categories-update permission.
     *
     * @param array<int> $ids Category IDs to update.
     * @return int Number of categories updated.
     */
    public function bulkEnableFeatured(array $ids): int
    {
        $this->requirePermission('categories-update');
        $count = Category::whereIn('id', $ids)->update(['featured' => true]);
        if ($count > 0) {
            $this->activityLogService->log(
                'Bulk enabled featured Categories',
                (string) $count,
                "{$count} category(ies) were set as featured."
            );
        }

        return $count;
    }

    /**
     * Bulk disable featured status for categories.
     *
     * Sets featured to false for all matching categories. Requires categories-update permission.
     *
     * @param array<int> $ids Category IDs to update.
     * @return int Number of categories updated.
     */
    public function bulkDisableFeatured(array $ids): int
    {
        $this->requirePermission('categories-update');
        $count = Category::whereIn('id', $ids)->update(['featured' => false]);
        if ($count > 0) {
            $this->activityLogService->log(
                'Bulk disabled featured Categories',
                (string) $count,
                "{$count} category(ies) were unset as featured."
            );
        }

        return $count;
    }

    /**
     * Bulk enable sync for categories.
     *
     * Sets is_sync_disable to false for all matching categories. Requires categories-update permission.
     *
     * @param array<int> $ids Category IDs to update.
     * @return int Number of categories updated.
     */
    public function bulkEnableSync(array $ids): int
    {
        $this->requirePermission('categories-update');
        $count = Category::whereIn('id', $ids)->update(['is_sync_disable' => false]);
        if ($count > 0) {
            $this->activityLogService->log(
                'Bulk enabled sync Categories',
                (string) $count,
                "{$count} category(ies) had sync enabled."
            );
        }

        return $count;
    }

    /**
     * Bulk disable sync for categories.
     *
     * Sets is_sync_disable to true for all matching categories. Requires categories-update permission.
     *
     * @param array<int> $ids Category IDs to update.
     * @return int Number of categories updated.
     */
    public function bulkDisableSync(array $ids): int
    {
        $this->requirePermission('categories-update');
        $count = Category::whereIn('id', $ids)->update(['is_sync_disable' => true]);
        if ($count > 0) {
            $this->activityLogService->log(
                'Bulk disabled sync Categories',
                (string) $count,
                "{$count} category(ies) had sync disabled."
            );
        }

        return $count;
    }

    /**
     * Import categories from an Excel or CSV file.
     *
     * Uses CategoriesImport for upsert logic. Requires categories-import permission.
     *
     * @param UploadedFile $file The uploaded import file.
     */
    public function importCategories(UploadedFile $file): void
    {
        $this->requirePermission('categories-import');
        Excel::import(new CategoriesImport(), $file);
    }

    /**
     * Export categories to Excel or PDF file.
     *
     * Supports download or email delivery. Requires categories-export permission.
     *
     * @param array<int> $ids Category IDs to export. Empty array exports all.
     * @param string $format Export format: 'excel' or 'pdf'.
     * @param User|null $user Recipient when method is 'email'. Required for email delivery.
     * @param array<string> $columns Column keys to include in export.
     * @param string $method Delivery method: 'download' or 'email'.
     * @return string Relative storage path of the generated file.
     * @throws RuntimeException When mail settings are not configured and method is 'email'.
     */
    public function exportCategories(array $ids, string $format, ?User $user, array $columns, string $method): string
    {
        $this->requirePermission('categories-export');

        $fileName = 'categories_' . now()->timestamp . '.' . ($format === 'pdf' ? 'pdf' : 'xlsx');
        $relativePath = 'exports/' . $fileName;

        if ($format === 'excel') {
            Excel::store(new CategoriesExport($ids, $columns), $relativePath, 'public');
        } else {
            $categories = Category::query()
                ->with('parent:id,name')
                ->when(! empty($ids), fn ($q) => $q->whereIn('id', $ids))
                ->get();

            $pdf = PDF::loadView('exports.categories-pdf', compact('categories', 'columns'));
            Storage::disk('public')->put($relativePath, $pdf->output());
        }

        if ($method === 'email' && $user) {
            $this->sendExportEmail($user, $relativePath, $fileName);
        }

        return $relativePath;
    }

    /**
     * Remove category image and icon from storage.
     *
     * @param Category $category The category instance.
     */
    private function cleanupFiles(Category $category): void
    {
        if ($category->image) {
            $this->uploadService->delete($category->image);
        }
        if ($category->icon) {
            $this->uploadService->delete($category->icon);
        }
    }

    /**
     * Process image and icon uploads and merge paths/URLs into category data.
     *
     * @param array<string, mixed> $data Input data containing optional 'image' and 'icon' as UploadedFile.
     * @return array<string, mixed> Data with image/icon paths and URLs set when uploaded.
     */
    private function handleFileUploads(array $data): array
    {
        if (isset($data['image']) && $data['image'] instanceof UploadedFile) {
            $path = $this->uploadService->upload(
                $data['image'],
                config('storage.categories.images', self::DEFAULT_CATEGORY_IMAGES_PATH)
            );
            $data['image'] = $path;
            $data['image_url'] = $this->uploadService->url($path);
        }

        if (isset($data['icon']) && $data['icon'] instanceof UploadedFile) {
            $path = $this->uploadService->upload(
                $data['icon'],
                config('storage.categories.icons', self::DEFAULT_CATEGORY_ICONS_PATH)
            );
            $data['icon'] = $path;
            $data['icon_url'] = $this->uploadService->url($path);
        }

        return $data;
    }

    /**
     * Send export completion email to the user.
     *
     * @param User $user Recipient of the export email.
     * @param string $path Relative storage path of the export file.
     * @param string $fileName Display filename for the attachment.
     * @throws RuntimeException When mail settings are not configured.
     */
    private function sendExportEmail(User $user, string $path, string $fileName): void
    {
        $mailSetting = MailSetting::default()->firstOr(
            fn () => throw new RuntimeException('Mail settings are not configured.')
        );
        $generalSetting = GeneralSetting::latest()->first();

        $this->setMailInfo($mailSetting);

        Mail::to($user->email)->send(
            new ExportMail($user, $path, $fileName, 'Categories List', $generalSetting)
        );
    }
}
