<?php

declare(strict_types=1);

namespace App\Imports;

use App\Models\Brand;
use Maatwebsite\Excel\Concerns\OnEachRow;
use Maatwebsite\Excel\Concerns\SkipsEmptyRows;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Maatwebsite\Excel\Concerns\WithValidation;
use Maatwebsite\Excel\Row;

/**
 * Excel/CSV import for Brand entities.
 *
 * Uses upsert logic: creates new brands or updates existing ones by name.
 * Slug is auto-generated by the Brand model. Skips empty rows.
 */
class BrandsImport implements OnEachRow, WithHeadingRow, SkipsEmptyRows, WithValidation
{
    /**
     * Process a single row from the import file.
     *
     * Skips rows with empty name. Uses updateOrCreate on name for upsert behavior.
     *
     * @param Row $row The current row being imported.
     */
    public function onRow(Row $row): void
    {
        $data = $row->toArray();
        $name = trim((string) ($data['name'] ?? ''));

        if ($name === '') {
            return;
        }

        Brand::updateOrCreate(
            ['name' => $name],
            [
                'short_description' => isset($data['short_description']) ? trim((string)$data['short_description']) : null,
                'image_url'         => isset($data['image_url']) ? trim((string)$data['image_url']) : null,
                'page_title'        => isset($data['page_title']) ? trim((string)$data['page_title']) : null,
                // If updating, we keep it active; if creating, it defaults to true
                'is_active'         => true,
            ]
        );
    }

    /**
     * Get validation rules for each row.
     *
     * @return array<string, array<int, string>> Validation rules keyed by column heading.
     */
    public function rules(): array
    {
        return [
            'name'      => ['required', 'string', 'max:255'],
            'image_url' => ['nullable', 'url'],
        ];
    }
}