<?php

declare(strict_types=1);

namespace App\Imports;

use App\Models\Category;
use Maatwebsite\Excel\Concerns\OnEachRow;
use Maatwebsite\Excel\Concerns\SkipsEmptyRows;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Maatwebsite\Excel\Concerns\WithValidation;
use Maatwebsite\Excel\Row;

/**
 * Excel/CSV import for Category entities.
 *
 * Uses upsert logic: creates new categories or updates existing ones by name.
 * Supports parent category via parentcategory column. Slug is auto-generated by the Category model.
 */
class CategoriesImport implements OnEachRow, WithHeadingRow, SkipsEmptyRows, WithValidation
{
    /**
     * Process a single row from the import file.
     *
     * Skips rows with empty name. Creates parent category if parentcategory column is provided.
     *
     * @param Row $row The current row being imported.
     */
    public function onRow(Row $row): void
    {
        $data = $row->toArray();
        $name = trim((string) ($data['name'] ?? ''));

        if ($name === '') {
            return;
        }

        $parentId = null;
        if (!empty($data['parentcategory'])) {
            $parentName = trim((string) $data['parentcategory']);
            $parent = Category::firstOrCreate(['name' => $parentName], ['is_active' => true]);
            $parentId = $parent->id;
        }

        Category::updateOrCreate(
            ['name' => $name],
            [
                'parent_id' => $parentId,
                'short_description' => isset($data['short_description']) ? trim((string) $data['short_description']) : null,
                'is_active' => true,
            ]
        );
    }

    /**
     * Get validation rules for each row.
     *
     * @return array<string, array<int, string>> Validation rules keyed by column heading.
     */
    public function rules(): array
    {
        return [
            'name' => ['required', 'string', 'max:255'],
            'short_description' => ['nullable', 'string', 'max:1000'],
            'parentcategory' => ['nullable', 'string', 'max:255'],
        ];
    }
}